---
chdir: "/home/deploy/web/code-maniacs/current"
environment: production
timeout: 30
wait: 30
log: "/home/deploy/web/code-maniacs/shared/log/thin.log"
pid: "/tmp/code-maniacs.pid"
max_conns: 1024
max_persistent_conns: 100
require: []
threadpool_size: 20
# servers: 2
servers: 1
daemonize: true
socket: "/tmp/code-maniacs.socket"
# port: 80
port: 3000
