default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: code_maniacs_development

production:
  <<: *default
  database: code_maniacs_production

# production:
#   <<: *default
#   database: rideray_production
#   username: rideray
#   password: <%= ENV['RIDERAY_DATABASE_PASSWORD'] %>
